import turtle as t
import math as m
a=t.Turtle()
screen=t.Screen()
screen.tracer(0,0)

def rectangle(hor,ver,col):
    a.pendown()  
    a.pencolor(col)
    for counter in range(1,3):
        a.forward(hor)
        a.left(90)
        a.forward(ver)
        a.left(90)
    a.penup() 
#khung vien
a.pensize(5)
a.penup()
a.goto(-200,-200)
rectangle(400,400,'light blue')
a.pensize(1)
#nen dat
a.penup()
a.setheading(0)
a.goto(200,-200)
a.pendown()
a.left(90)
a.pencolor('black')
a.fillcolor('#9A3F2B')
a.begin_fill()
a.circle(200,180)
a.end_fill()
#duong di
x=130
a.penup()
a.home()
a.goto(-60,-200)
a.left(80)
a.pendown()
a.fillcolor('light grey')
a.begin_fill()
a.forward(x)
a.right(80)
a.forward(120-2*(x*m.cos(m.radians(80))))
a.right(80)
a.forward(x)
a.end_fill()
#khung nha
u=120
v=200-(x*m.sin(m.radians(80)))
a.penup()
a.goto(-u,-v)
a.pendown()
a.fillcolor('#BD9F98')
a.begin_fill()
a.setheading(0)
a.forward(2*u)
a.goto(u,-v)
a.goto(u,v)
b=a.distance(0,1.25*u)
a.goto(0,1.25*u)
a.goto(-u,v)
a.goto(-u,-v)
a.end_fill()
#cua so trai
a.penup()
a.goto(-u*3/4,-v/2)
a.fillcolor('white')
a.begin_fill()
rectangle(u/3,u/3,'black')
a.end_fill()
a.penup()
a.left(90)
a.forward(u/6)
a.right(90)
a.pendown()
a.forward(u/3)
a.backward(u/6)
a.left(90)
a.forward(u/6)
a.backward(u/3)
#cua so 2
a.penup()
a.goto(u*3/4,-v/2)
a.fillcolor('white')
a.begin_fill()
rectangle(u/3,u/3,'black')
a.end_fill()
a.penup()
a.left(90)
a.forward(u/6)
a.right(90)
a.pendown()
a.forward(u/3)
a.backward(u/6)
a.left(90)
a.forward(u/6)
a.backward(u/3)
#cua so 3
a.penup()
a.goto(-u/6,v)
a.setheading(0)
a.fillcolor('white')
a.begin_fill()
rectangle(u/3,u/3,'black')
a.end_fill()
a.penup()
a.left(90)
a.forward(u/6)
a.right(90)
a.pendown()
a.forward(u/3)
a.backward(u/6)
a.left(90)
a.forward(u/6)
a.backward(u/3)
#cua chinh
a.penup()
a.setheading(0)
a.goto(-(60-x*m.cos(m.radians(80))),-v)
a.pendown()
a.fillcolor('#4F6EA3')
a.begin_fill()
rectangle(2*(60-x*m.cos(m.radians(80))),1.5*v,'black')
a.end_fill()
#mai nha
b+=15
c=10
a.penup()
a.setheading(0)
a.goto(-u,v)
q=a.towards(0,1.25*u)
a.goto(0,1.25*u)
a.pendown()
a.fillcolor('red')
a.begin_fill()
a.left(q)
a.back(b)
a.left(90)
a.forward(c)
a.right(90)
a.forward(b+c*1/(m.tan(m.radians(90-q))))
a.right(2*q)
a.forward(b+c*1/(m.tan(m.radians(90-q))))
a.right(90)
a.forward(c)
a.right(90)
a.goto(0,1.25*u)
a.end_fill()
#mat troi
a.penup()
a.setheading(0)
a.goto(150,120)
a.pendown()
a.fillcolor('yellow')
a.pencolor('red')
a.begin_fill()
a.circle(20)
a.end_fill()
a.right(90)
a.penup()
a.back(20)
a.pendown()
for i in range(12):
    a.penup()
    a.forward(20)
    a.pendown()
    a.forward(15)
    a.penup()
    a.back(35)
    a.left(30)
a.hideturtle()
t.done()